name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

# 添加必要的权限
permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # 只保留 Windows 构建
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win
        env:
          # Electron Builder 需要 GH_TOKEN 来发布
          GH_TOKEN: ${{ github.token }}

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          # 自动生成发布说明
          generate_release_notes: true
          # 文件上传模式
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
          # 如果没有匹配的文件则失败
          fail_on_unmatched_files: false
          # 覆盖已存在的文件
          overwrite_files: true
          # 设置为最新版本
          make_latest: true
        # softprops/action-gh-release 使用 GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ github.token }}
